name: Terraform S3 Bucket Provisioning with Approval

on:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    name: Terraform Plan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Plan Output
        run: |
          echo "::set-output name=plan_output::$(terraform show -json tfplan > tfplan.json)"
        id: plan

      - name: Upload Plan for Apply Job
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

  terraform_apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    needs: terraform_plan
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan
